#! /usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;

$| = 1;             # unbuffered STDOUT

GetOptions(
    \my %OPT,
    'interval=i',
    'random',
) or exit 255;

die "(E) No interval specified.\n"  unless $OPT{interval};


while ( 1 ) {
    my $time = $OPT{random} ? int(rand $OPT{interval}) + 1 : $OPT{interval};

    print "$time - ", scalar(localtime), "\n";

    sleep $time;
}

__END__

